### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by NanyangTaiji** [Tans5/tMediaPlayer#1]
no video/audio shown up on Oppo A74 (android 13)
crashed on Huawei MediaPad M5 Pro (android 9) in video/audio loading

**Comment by Tans5** [comment]
Oppo phone check video/audio read permission.
Huawei MediaPad M5 Pro check supported gl version, app need open gl 3.0.

**Comment by Tans5** [comment]
Could you get any error logs?
