### ISSUE TITLE
通过Socket传过来的H.264视频流可以播放吗？

### ISSUE THREAD

**Issue by ulongx** [Tans5/tMediaPlayer#2]
两台Android通过Socket连接后，把相机视频流通过MediaCodec H.264编码后, 传过来的视频流，可以播放吗？

**Comment by Tans5** [comment]
可以用 MediaCodec 播放，我以前这么干过。

**Comment by ulongx** [comment]
> 可以用 MediaCodec 播放，我以前这么干过。

嗯谢谢，我现在也是这么做的，不过在低配置机器上画面有延迟和画面卡顿，不知道什么原因。

**Comment by Tans5** [comment]
可能是网络问题吧，低配的手机 WiFi 的硬件可能差点，试试降低分辨率。

**Comment by ulongx** [comment]
> 可能是网络问题吧，低配的手机 WiFi 的硬件可能差点，试试降低分辨率。

好的谢谢，我尝试优化一下
